---
engine: knitr
title: Club meetings
---

# Welcome

- Welcome to the Deep Learning with Python (3e) book club! 
- book: [deeplearningwithpython.io](https://deeplearningwithpython.io)
- These slides are available at [dslc.io/deeppy](https://dslc.io/deeppy).
- We follow the [Data Science Learning Community Code of Conduct](https://dslc.io/code_of_conduct.html).

::: notes
- You can add notes on each slide with blocks like this!
- Load a deck in the browser and type "s" to see these notes.
:::

## Book club meetings

-   Volunteer leads discussion of a chapter
    -   **This is the best way to learn the material.**
-   Presentations: 
    -   Review of material
    -   Questions you have
    -   Maybe live demo (Google Colab)

## How to edit the slides: 

-   More info about editing: [this github repo](https://github.com/r4ds/bookclub-deeppy)
-   Recorded, available on the [Data Science Learning Community YouTube Channel (DSLC.video)](http://dslc.video)

## Pace

-   **Goal:** 1 chapter/week
-   Ok to split overwhelming chapters
-   Ok to combine short chapters
-   Meet ***every*** week except holidays, etc
    -   We will meet even if scheduled presenter unavailable
-   Slack is good place for offline discussion/troubleshooting  

## Learning objectives (LOs)

-   Students who study with LOs in mind ***retain more***
-   **Tips:**
    -   Think "After today's session, you will be able to {LO}"
    -   *Very* roughly **1 per heading**

## Group introductions

- If you feel comfortable sharing:
  - Who are you?
  - Where you calling in from? (If you're not comfortable sharing, skip)
  - How long have you been using Python?
  - What was your introduction to Python?
  - What are you most looking forward to during the club?
